"""Initial migration.

Revision ID: 247d2fb7b84c
Revises: 
Create Date: 2021-08-27 14:33:01.742716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '247d2fb7b84c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stadium')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stadium',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('team', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='stadium_pkey')
    )
    # ### end Alembic commands ###
