"""Second.

Revision ID: 33179de31b77
Revises: 247d2fb7b84c
Create Date: 2021-08-27 14:43:15.689424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33179de31b77'
down_revision = '247d2fb7b84c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('ref', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client')
    # ### end Alembic commands ###
