"""third

Revision ID: 872d068e7c85
Revises: 33179de31b77
Create Date: 2021-08-27 14:44:23.146208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '872d068e7c85'
down_revision = '33179de31b77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('ref', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='client_pkey')
    )
    # ### end Alembic commands ###
